version: '3'
services:
    db:
      image: postgres
      container_name: postgres
      environment:
        POSTGRES_PASSWORD: test
      ports:
        - 5432:5432
      networks:
        - net
networks:
  net: